# Tenseurs et opérations de base
________________________________

Dans ce cours, nous allons voir comment travailler avec des tenseurs : **comment en créer et effectuer des opérations basiques, comment convertir un numpy array en pytorch tenseur et vice-versa.**

Sur PyTorch, tout est basé sur l'utilisation des tenseurs et leurs différentes applications. Depuis Numpy, vous connaissez probablement les arrays et vecteurs, mais en PyTorch tout est en tenseur. Un tenseur est généralement une fonction des coordonnées de l'espace, défini dans un espace à n dimensions par nk composantes, où k est l'ordre du tenseur.

Dans l'espace euclidien à trois dimensions, un tenseur d'ordre zéro est un scalaire, un tenseur d'ordre un est un vecteur, un tenseur d'ordre 2 est une matrice.

Tout d'abord, importons le module PyTorch.

In [1]:
import torch

Ensuite, créons un tenseur vide d'ordre 0, qui est égal à un scalaire.

In [2]:
x = torch.empty(1)
x

tensor([0.])

Si on remplace 1 par 3, on obtient un tenseur de dimension 1 avec trois valeurs, ce qui correspond à un vecteur à 3 valeurs.

In [3]:
x = torch.empty(3)
x

tensor([3.3733e-06, 1.6985e+22, 1.7488e-04])

Pour augmenter l'ordre, il suffit d'ajouter des valeurs en paramètre dans la fonction ___empty()___. Par exemple, si je veux créer une matrice (donc un tenseur d'ordre deux) :

In [4]:
x = torch.empty(3, 2)
x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

Ou bien un tenseur d'ordre 3 :

In [5]:
x = torch.empty(3, 2, 2)
x

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

Nous pouvons créer aussi des tenseurs avec des valeurs aléatoire à l'aide de la fonction ___rand()___:

In [6]:
x = torch.rand(3, 2)
x

tensor([[0.0625, 0.3383],
        [0.3284, 0.5482],
        [0.3496, 0.3159]])

Nous pouvons créer des tenseurs vides, avec des valeurs nulles à l'aide de la fonction ___zeros()___, ou bien des tenseurs rempli avec des valeurs égales à 1 à l'aide de la fonction ___ones()___ :

In [7]:
x = torch.zeros(3, 2)
x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [8]:
x = torch.ones(3, 2)
x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

Nous pouvons changer le type de données des tenseurs, et vérifier si le changement de type a bien été effectué :

In [9]:
x.dtype

torch.float32

In [10]:
x = torch.ones(3, 2, dtype = torch.double)
x.dtype

torch.float64

Il existe plusieurs types de données : _float16, float32, double (float64)..._

Nous pouvons aussi jeter un oeil sur la taille du tenseur avec la fonction ___size()___ :

In [11]:
x.size()

torch.Size([3, 2])

Nous pouvons créer un tenseur à partir d'une liste Python avec la fonction ___tensor():___

In [12]:
x = torch.tensor([2.5, 0.1])
x

tensor([2.5000, 0.1000])

Bien, maintenant vous savez comment créer des tenseurs à partir de PyTorch ! Voyons maintenant comment les utiliser avec des opérations de base.

Créons deux tenseurs aléatoires d'ordre 2 avec deux valeurs dans chaque dimension, et essayons quelques opérations classiques.

In [13]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
x, y

(tensor([[0.9653, 0.7143],
         [0.5317, 0.6396]]),
 tensor([[0.7258, 0.6006],
         [0.7952, 0.4469]]))

Additionnons les deux tenseurs et voyons le résultat :

In [14]:
z = x + y
z

tensor([[1.6910, 1.3149],
        [1.3268, 1.0864]])

Chacune des entrées ont étés additionnées ensembles dans z. Nous pouvons aussi utiliser la fonction ___add()___ pour avoir le même résultat :

In [15]:
z = torch.add(x, y)
z

tensor([[1.6910, 1.3149],
        [1.3268, 1.0864]])

Nous pouvons aussi additionner l'un des tenseurs dans l'autre sans créer une nouvelle variable :

In [16]:
y.add_(x)

tensor([[1.6910, 1.3149],
        [1.3268, 1.0864]])

Par ailleurs dans PyTorch, toutes les fonctions avec un underscore vont modifier la variable sans en créer une nouvelle.

Après les additions, nous pouvons soustraire les tenseurs entre eux, facilité avec la fonction ___sub()___ :

In [17]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
x, y

(tensor([[0.2902, 0.0284],
         [0.9723, 0.8154]]),
 tensor([[0.2636, 0.2296],
         [0.6941, 0.1326]]))

In [18]:
z = torch.sub(x, y)
z

tensor([[ 0.0266, -0.2012],
        [ 0.2782,  0.6828]])

In [19]:
x.sub_(y)

tensor([[ 0.0266, -0.2012],
        [ 0.2782,  0.6828]])

Nous avons ensuite les multiplications avec la fonction ___mul()___ :

In [20]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
x, y

(tensor([[0.0214, 0.5336],
         [0.6035, 0.3309]]),
 tensor([[0.6482, 0.6827],
         [0.3811, 0.6995]]))

In [21]:
z = torch.mul(x, y)
z

tensor([[0.0139, 0.3643],
        [0.2300, 0.2315]])

In [22]:
y.mul_(x)

tensor([[0.0139, 0.3643],
        [0.2300, 0.2315]])

Et enfin les divisions avec la fonction ___div()___ :

In [23]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
x, y

(tensor([[0.0802, 0.0654],
         [0.6071, 0.4018]]),
 tensor([[0.1325, 0.7295],
         [0.5207, 0.7536]]))

In [24]:
z = torch.div(x, y)
z

tensor([[0.6050, 0.0896],
        [1.1659, 0.5332]])

In [25]:
x.div_(y)

tensor([[0.6050, 0.0896],
        [1.1659, 0.5332]])

Voici toutes les opérations de base que l'on peut faire avec les tenseurs !

Nous pouvons faire des opérations de filtrage sur les tenseurs, comme l'on peut faire sur des Numpy arrays:

In [26]:
x = torch.rand(5, 3)
x

tensor([[0.5328, 0.7087, 0.5004],
        [0.6323, 0.6642, 0.8196],
        [0.1599, 0.5360, 0.6228],
        [0.5296, 0.3211, 0.0084],
        [0.5596, 0.0684, 0.9368]])

In [27]:
# Nous voulons toutes les lignes mais uniquement la première colonne
x[:, 0]

tensor([0.5328, 0.6323, 0.1599, 0.5296, 0.5596])

In [28]:
# Nous voulons toutes les colonnes mais uniquement la première ligne 
x[0, :]

tensor([0.5328, 0.7087, 0.5004])

In [29]:
# Nous voulons l'élément de la deuxième ligne, première colonne
x[1, 0]

tensor(0.6323)

In [30]:
# Si ce nouveau tenseur contient un unique élément, nous pouvons l'appeler avec la fonction item()
x[1, 0].item()

0.6322949528694153

Nous pouvons aussi remodifier la forme de nos tenseurs avec la fonction view() :

In [31]:
x = torch.rand(4, 4)
x

tensor([[0.1671, 0.3585, 0.0103, 0.8911],
        [0.5023, 0.0144, 0.4083, 0.6087],
        [0.7722, 0.4964, 0.8382, 0.3317],
        [0.0788, 0.7028, 0.5497, 0.4717]])

In [32]:
# Ici, nous demandons à voir les 16 éléments dans une seule dimension
y = x.view(16)
y

tensor([0.1671, 0.3585, 0.0103, 0.8911, 0.5023, 0.0144, 0.4083, 0.6087, 0.7722,
        0.4964, 0.8382, 0.3317, 0.0788, 0.7028, 0.5497, 0.4717])

In [33]:
# Ici, nous demandons à voir les 16 éléments dans une matrice de 8x2
y = x.view(-1, 8)
y

tensor([[0.1671, 0.3585, 0.0103, 0.8911, 0.5023, 0.0144, 0.4083, 0.6087],
        [0.7722, 0.4964, 0.8382, 0.3317, 0.0788, 0.7028, 0.5497, 0.4717]])

In [34]:
# Ici nous demandons à voir les 16 éléments dans une matrice de 2x8
y = x.view(-1, 2)
y

tensor([[0.1671, 0.3585],
        [0.0103, 0.8911],
        [0.5023, 0.0144],
        [0.4083, 0.6087],
        [0.7722, 0.4964],
        [0.8382, 0.3317],
        [0.0788, 0.7028],
        [0.5497, 0.4717]])

Pour convertir un pytorch tenseur en numpy array, c'est très simple. 

Tout d'abord, importons le module numpy.

In [35]:
import numpy as np

In [36]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [37]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [38]:
type(b)

numpy.ndarray

On remarque que b est bien un numpy array.

Cependant faites attention, si le tenseur est sur le CPU et non sur le GPU, les deux objets partagerons le même chemin sur la mémoire : si on modifie l'un des objets, on modifie aussi l'autre : 

In [39]:
c = torch.tensor([0.5, 0.5, 0.5, 0.5, 0.5])
a.sub_(c)

tensor([0.5000, 0.5000, 0.5000, 0.5000, 0.5000])

In [40]:
b

array([0.5, 0.5, 0.5, 0.5, 0.5], dtype=float32)

On remarque qu'en modifiant l'objet "a", l'objet "b" a lui aussi été modifié.

Pour changer un numpy array en pytorch tenseur, il suffit de réutiliser la fonction ___tensor()___ de pytorch:

In [41]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [42]:
b = torch.tensor(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [43]:
type(b)

torch.Tensor

Nous pouvons aussi utiliser la fonction ___from_numpy()___ :

In [44]:
c = torch.from_numpy(a)
c

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [45]:
type(c)

torch.Tensor

Ici aussi, si l'array est sur le CPU et non sur le GPU, les deux objets partagerons le même chemin sur la mémoire : si on modifie l'un des objets, on modifie aussi l'autre. Donc faites attention !

Si jamais vous avez installé CUDA Toolkit, vous pouvez créer les tenseurs sur votre GPU (et donc évitez que les deux objets partagent le même chemin). Pour ce faire, vous devez spécifier votre machine en utilisant la fonction ___device()___ : 

In [46]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    
z

tensor([2., 2., 2., 2., 2.], device='cuda:0')

L'autre avantage d'utiliser le GPU est la rapidité d'exécution des commandes (en fonction de votre GPU, bien entendu). Mais faites attention car les numpy arrays ne peuvent utiliser que les tenseur CPU, donc il faut passer les tenseurs sur la mémoire du CPU.

In [47]:
z = z.to("cpu")
z.numpy()

array([2., 2., 2., 2., 2.], dtype=float32)

Beaucoup de fois dans les pages de codes sur Internet, lorsqu'un tenseur est créé, on retrouve souvent l'argument "_requites_grad=True_" qui est sur False par défaut. Cela permet de demander à PyTorch de calculer le gradient du tenseur pour les étapes d'optimisation de l'IA. En prévision des futures lignes de codes que vous allez écrire, il est important de calculer les gradients pour pouvoir optimiser votre code, donc n'oubliez pas d'ajouter cet argument !

____________________________________________________________________________________________________________________________________________________________________________________________________________

C'est la fin de ce cours sur les opérations de base sur les tenseurs, merci à vous d'avoir été attentif et on se retrouve sur le prochain cours : le calcul des gradients avec Autograd !